package sodium

import "github.com/veandco/go-sdl2/sdl"

const (
	INIT_EVERYTHING      = sdl.INIT_EVERYTHING
	WINDOW_SHOWN         = sdl.WINDOW_SHOWN
	WINDOW_FULLSCREEN    = sdl.WINDOW_FULLSCREEN
	WINDOW_HIDDEN        = sdl.WINDOW_HIDDEN
	WINDOW_BORDERLESS    = sdl.WINDOW_BORDERLESS
	WINDOW_RESIZABLE     = sdl.WINDOW_RESIZABLE
	WINDOW_ALWAYS_ON_TOP = sdl.WINDOW_ALWAYS_ON_TOP
	WINDOWPOS_UNDEFINED  = sdl.WINDOWPOS_UNDEFINED
)
